### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by lsh1994** [erdongsanshi/Fuss-Free-structure#2]
readme中的数据准备所用数据需要申请，麻烦通过一下。或者转为公开数据？谢谢
![image](https://github.com/erdongsanshi/FFNet/assets/14355014/abd56391-bc51-4f6e-80da-d8cb4e58b1ec)

**Comment by lsh1994** [comment]
直接使用官方的sha数据，遇到错误：    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
number of img [train]: 0
number of img [val]: 0

**Comment by erdongsanshi** [comment]
Permissions are now open

**Comment by erdongsanshi** [comment]
@lsh1994 Permissions are now open
